replicaCount: 1
image:
  useImagePullSecrets: true
  pullPolicy: Always
  repository: delphiacr.azurecr.io/delphi/delphi_springboot
service:
  internalPort: 8080
  externalPort: 8080
ingress:
  enabled: true
  basedomain: delphik8s-ddc653a3.hcp.westus.azmk8s.io