trigger: none
pr: none

variables:
- template: cd-vars.yaml
  parameters:
      projectName: delphi
      registryName: delphiacr
      aks: delphi_k8s
      rg: DelphiRG
      acrlogin_username: delphiacr
      clientid: f0720042-c733-4d7f-a84a-803b3b7df068
      clientsecret: 13003584-1682-4634-bab4-f5d68a7f013e
      tenantid: 93bb4c86-1f5b-48e6-b8c1-b46d17b15c0a
      k8sNamespace: delphi_k8s

resources: 
  pipelines:
  - pipeline: ci-pipeline
    source: delphi_task-ci
    trigger:
      enabled: true
      branches:
        include:
          - master

stages:
- stage: development
  displayName: development
  jobs:
  - deployment: development
    variables:
      k8sNamespace: 'delphi_k8s'
    displayName: deploy helm chart into AKS
    pool:
      vmImage: 'ubuntu-16.04'
    environment: development-$(projectName)
    strategy:
      runOnce:
        deploy:
          steps:
          - template: cd-steps.yaml
