trigger:
  batch: true
  branches:
    include: 
    - '*'
  paths:
    include:
    - ci-steps.yaml
    
pr: none

pool:
  vmImage: 'ubuntu-16.04'

variables:
- template: ci-vars.yaml
  parameters:
      projectName: delphi_task
      registryName: delphiacr
      imageName: delphi_springboot
      clientid: f0720042-c733-4d7f-a84a-803b3b7df068
      clientsecret: 13003584-1682-4634-bab4-f5d68a7f013e
      tenantid: 93bb4c86-1f5b-48e6-b8c1-b46d17b15c0a
      acrlogin_username: delphiacr
      helmChartVersion: v0.3.0

steps:
- template: ci-steps.yaml