trigger:
  batch: true
  branches:
    include: 
    - '*'
  paths:
    include: 
    - delphi_task/
    - ci-steps.yaml
    
pr: none

- task: AzureKeyVault@1
  inputs:
    azureSubscription: 'Azure subscription (e6c064af-4de4-4ebc-a459-e193bfe6e9bf)'
    KeyVaultName: 'delphivault'
    SecretsFilter: '*'

pool:
  vmImage: 'ubuntu-16.04'

variables:
- template: ci-vars.yaml
  parameters:
      projectName: delphi_task
      registryName: delphiacr
      imageName: delphi_springboot

steps:
- template: ci-steps.yaml