{{ if .Values.image.private }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Chart.Name }}-acr-secret
type: kubernetes.io/service-account-token
data:
  .service-account-token: {{ template "imagePullSecret" . }}
{{ end }}